<?php
/**
 * Build
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DeadlockApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deadlock Data API
 *
 * API for Deadlock game data, containing builds and active matches
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DeadlockApi\Model;

use \ArrayAccess;
use \DeadlockApi\ObjectSerializer;

/**
 * Build Class Doc Comment
 *
 * @category Class
 * @package  DeadlockApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Build implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Build';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'hero_build' => '\DeadlockApi\Model\BuildHero',
        'num_favorites' => 'int',
        'num_ignores' => 'int',
        'num_reports' => 'int',
        'preference' => '\DeadlockApi\Model\BuildPreference'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'hero_build' => null,
        'num_favorites' => null,
        'num_ignores' => null,
        'num_reports' => null,
        'preference' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'hero_build' => false,
        'num_favorites' => false,
        'num_ignores' => false,
        'num_reports' => false,
        'preference' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'hero_build' => 'hero_build',
        'num_favorites' => 'num_favorites',
        'num_ignores' => 'num_ignores',
        'num_reports' => 'num_reports',
        'preference' => 'preference'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'hero_build' => 'setHeroBuild',
        'num_favorites' => 'setNumFavorites',
        'num_ignores' => 'setNumIgnores',
        'num_reports' => 'setNumReports',
        'preference' => 'setPreference'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'hero_build' => 'getHeroBuild',
        'num_favorites' => 'getNumFavorites',
        'num_ignores' => 'getNumIgnores',
        'num_reports' => 'getNumReports',
        'preference' => 'getPreference'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('hero_build', $data ?? [], null);
        $this->setIfExists('num_favorites', $data ?? [], null);
        $this->setIfExists('num_ignores', $data ?? [], null);
        $this->setIfExists('num_reports', $data ?? [], null);
        $this->setIfExists('preference', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['hero_build'] === null) {
            $invalidProperties[] = "'hero_build' can't be null";
        }
        if ($this->container['num_favorites'] === null) {
            $invalidProperties[] = "'num_favorites' can't be null";
        }
        if ($this->container['num_ignores'] === null) {
            $invalidProperties[] = "'num_ignores' can't be null";
        }
        if ($this->container['num_reports'] === null) {
            $invalidProperties[] = "'num_reports' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets hero_build
     *
     * @return \DeadlockApi\Model\BuildHero
     */
    public function getHeroBuild()
    {
        return $this->container['hero_build'];
    }

    /**
     * Sets hero_build
     *
     * @param \DeadlockApi\Model\BuildHero $hero_build hero_build
     *
     * @return self
     */
    public function setHeroBuild($hero_build)
    {
        if (is_null($hero_build)) {
            throw new \InvalidArgumentException('non-nullable hero_build cannot be null');
        }
        $this->container['hero_build'] = $hero_build;

        return $this;
    }

    /**
     * Gets num_favorites
     *
     * @return int
     */
    public function getNumFavorites()
    {
        return $this->container['num_favorites'];
    }

    /**
     * Sets num_favorites
     *
     * @param int $num_favorites num_favorites
     *
     * @return self
     */
    public function setNumFavorites($num_favorites)
    {
        if (is_null($num_favorites)) {
            throw new \InvalidArgumentException('non-nullable num_favorites cannot be null');
        }
        $this->container['num_favorites'] = $num_favorites;

        return $this;
    }

    /**
     * Gets num_ignores
     *
     * @return int
     */
    public function getNumIgnores()
    {
        return $this->container['num_ignores'];
    }

    /**
     * Sets num_ignores
     *
     * @param int $num_ignores num_ignores
     *
     * @return self
     */
    public function setNumIgnores($num_ignores)
    {
        if (is_null($num_ignores)) {
            throw new \InvalidArgumentException('non-nullable num_ignores cannot be null');
        }
        $this->container['num_ignores'] = $num_ignores;

        return $this;
    }

    /**
     * Gets num_reports
     *
     * @return int
     */
    public function getNumReports()
    {
        return $this->container['num_reports'];
    }

    /**
     * Sets num_reports
     *
     * @param int $num_reports num_reports
     *
     * @return self
     */
    public function setNumReports($num_reports)
    {
        if (is_null($num_reports)) {
            throw new \InvalidArgumentException('non-nullable num_reports cannot be null');
        }
        $this->container['num_reports'] = $num_reports;

        return $this;
    }

    /**
     * Gets preference
     *
     * @return \DeadlockApi\Model\BuildPreference|null
     */
    public function getPreference()
    {
        return $this->container['preference'];
    }

    /**
     * Sets preference
     *
     * @param \DeadlockApi\Model\BuildPreference|null $preference preference
     *
     * @return self
     */
    public function setPreference($preference)
    {
        if (is_null($preference)) {
            array_push($this->openAPINullablesSetToNull, 'preference');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('preference', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['preference'] = $preference;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


