<?php
/**
 * Language
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DeadlockApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deadlock Assets API
 *
 * API for Deadlock assets, including hero stats and images, and item stats and images.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DeadlockApi\Model;
use \DeadlockApi\ObjectSerializer;

/**
 * Language Class Doc Comment
 *
 * @category Class
 * @package  DeadlockApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Language
{
    /**
     * Possible values of this enum
     */
    public const BRAZILIAN = 'brazilian';

    public const BULGARIAN = 'bulgarian';

    public const CZECH = 'czech';

    public const DANISH = 'danish';

    public const DUTCH = 'dutch';

    public const ENGLISH = 'english';

    public const FINNISH = 'finnish';

    public const FRENCH = 'french';

    public const GERMAN = 'german';

    public const GREEK = 'greek';

    public const HUNGARIAN = 'hungarian';

    public const INDONESIAN = 'indonesian';

    public const ITALIAN = 'italian';

    public const JAPANESE = 'japanese';

    public const KOREANA = 'koreana';

    public const LATAM = 'latam';

    public const NORWEGIAN = 'norwegian';

    public const POLISH = 'polish';

    public const PORTUGUESE = 'portuguese';

    public const ROMANIAN = 'romanian';

    public const RUSSIAN = 'russian';

    public const SCHINESE = 'schinese';

    public const SPANISH = 'spanish';

    public const SWEDISH = 'swedish';

    public const TCHINESE = 'tchinese';

    public const THAI = 'thai';

    public const TURKISH = 'turkish';

    public const UKRAINIAN = 'ukrainian';

    public const VIETNAMESE = 'vietnamese';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BRAZILIAN,
            self::BULGARIAN,
            self::CZECH,
            self::DANISH,
            self::DUTCH,
            self::ENGLISH,
            self::FINNISH,
            self::FRENCH,
            self::GERMAN,
            self::GREEK,
            self::HUNGARIAN,
            self::INDONESIAN,
            self::ITALIAN,
            self::JAPANESE,
            self::KOREANA,
            self::LATAM,
            self::NORWEGIAN,
            self::POLISH,
            self::PORTUGUESE,
            self::ROMANIAN,
            self::RUSSIAN,
            self::SCHINESE,
            self::SPANISH,
            self::SWEDISH,
            self::TCHINESE,
            self::THAI,
            self::TURKISH,
            self::UKRAINIAN,
            self::VIETNAMESE
        ];
    }
}


