<?php
/**
 * DataClient
 * PHP version 7.4
 *
 * @category Class
 * @package  DeadlockApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deadlock Data API
 *
 * API for Deadlock game data, containing builds and active matches
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace DeadlockApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use DeadlockApi\ApiException;
use DeadlockApi\Configuration;
use DeadlockApi\HeaderSelector;
use DeadlockApi\ObjectSerializer;

/**
 * DataClient Class Doc Comment
 *
 * @category Class
 * @package  DeadlockApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DataClient
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getActiveMatchesV1ActiveMatchesGet' => [
            'application/json',
        ],
        'getBuildV1BuildsBuildIdGet' => [
            'application/json',
        ],
        'getBuildsByHeroIdV1BuildsByHeroIdHeroIdGet' => [
            'application/json',
        ],
        'getBuildsByHeroNameV1BuildsByHeroNameHeroNameGet' => [
            'application/json',
        ],
        'getBuildsV1BuildsGet' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getActiveMatchesV1ActiveMatchesGet
     *
     * Get Active Matches
     *
     * @param  bool $parse_objectives parse_objectives (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getActiveMatchesV1ActiveMatchesGet'] to see the possible values for this operation
     *
     * @throws \DeadlockApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \DeadlockApi\Model\ActiveMatch[]|\DeadlockApi\Model\HTTPValidationError
     */
    public function getActiveMatchesV1ActiveMatchesGet($parse_objectives = false, string $contentType = self::contentTypes['getActiveMatchesV1ActiveMatchesGet'][0])
    {
        list($response) = $this->getActiveMatchesV1ActiveMatchesGetWithHttpInfo($parse_objectives, $contentType);
        return $response;
    }

    /**
     * Operation getActiveMatchesV1ActiveMatchesGetWithHttpInfo
     *
     * Get Active Matches
     *
     * @param  bool $parse_objectives (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getActiveMatchesV1ActiveMatchesGet'] to see the possible values for this operation
     *
     * @throws \DeadlockApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \DeadlockApi\Model\ActiveMatch[]|\DeadlockApi\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getActiveMatchesV1ActiveMatchesGetWithHttpInfo($parse_objectives = false, string $contentType = self::contentTypes['getActiveMatchesV1ActiveMatchesGet'][0])
    {
        $request = $this->getActiveMatchesV1ActiveMatchesGetRequest($parse_objectives, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\DeadlockApi\Model\ActiveMatch[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\DeadlockApi\Model\ActiveMatch[]' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\DeadlockApi\Model\ActiveMatch[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\DeadlockApi\Model\HTTPValidationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\DeadlockApi\Model\HTTPValidationError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\DeadlockApi\Model\HTTPValidationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\DeadlockApi\Model\ActiveMatch[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DeadlockApi\Model\ActiveMatch[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DeadlockApi\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getActiveMatchesV1ActiveMatchesGetAsync
     *
     * Get Active Matches
     *
     * @param  bool $parse_objectives (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getActiveMatchesV1ActiveMatchesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getActiveMatchesV1ActiveMatchesGetAsync($parse_objectives = false, string $contentType = self::contentTypes['getActiveMatchesV1ActiveMatchesGet'][0])
    {
        return $this->getActiveMatchesV1ActiveMatchesGetAsyncWithHttpInfo($parse_objectives, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getActiveMatchesV1ActiveMatchesGetAsyncWithHttpInfo
     *
     * Get Active Matches
     *
     * @param  bool $parse_objectives (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getActiveMatchesV1ActiveMatchesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getActiveMatchesV1ActiveMatchesGetAsyncWithHttpInfo($parse_objectives = false, string $contentType = self::contentTypes['getActiveMatchesV1ActiveMatchesGet'][0])
    {
        $returnType = '\DeadlockApi\Model\ActiveMatch[]';
        $request = $this->getActiveMatchesV1ActiveMatchesGetRequest($parse_objectives, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getActiveMatchesV1ActiveMatchesGet'
     *
     * @param  bool $parse_objectives (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getActiveMatchesV1ActiveMatchesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getActiveMatchesV1ActiveMatchesGetRequest($parse_objectives = false, string $contentType = self::contentTypes['getActiveMatchesV1ActiveMatchesGet'][0])
    {



        $resourcePath = '/v1/active-matches';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $parse_objectives,
            'parse_objectives', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getBuildV1BuildsBuildIdGet
     *
     * Get Build
     *
     * @param  int $build_id build_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildV1BuildsBuildIdGet'] to see the possible values for this operation
     *
     * @throws \DeadlockApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \DeadlockApi\Model\Build|\DeadlockApi\Model\HTTPValidationError
     */
    public function getBuildV1BuildsBuildIdGet($build_id, string $contentType = self::contentTypes['getBuildV1BuildsBuildIdGet'][0])
    {
        list($response) = $this->getBuildV1BuildsBuildIdGetWithHttpInfo($build_id, $contentType);
        return $response;
    }

    /**
     * Operation getBuildV1BuildsBuildIdGetWithHttpInfo
     *
     * Get Build
     *
     * @param  int $build_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildV1BuildsBuildIdGet'] to see the possible values for this operation
     *
     * @throws \DeadlockApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \DeadlockApi\Model\Build|\DeadlockApi\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBuildV1BuildsBuildIdGetWithHttpInfo($build_id, string $contentType = self::contentTypes['getBuildV1BuildsBuildIdGet'][0])
    {
        $request = $this->getBuildV1BuildsBuildIdGetRequest($build_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\DeadlockApi\Model\Build' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\DeadlockApi\Model\Build' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\DeadlockApi\Model\Build', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\DeadlockApi\Model\HTTPValidationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\DeadlockApi\Model\HTTPValidationError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\DeadlockApi\Model\HTTPValidationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\DeadlockApi\Model\Build';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DeadlockApi\Model\Build',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DeadlockApi\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getBuildV1BuildsBuildIdGetAsync
     *
     * Get Build
     *
     * @param  int $build_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildV1BuildsBuildIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBuildV1BuildsBuildIdGetAsync($build_id, string $contentType = self::contentTypes['getBuildV1BuildsBuildIdGet'][0])
    {
        return $this->getBuildV1BuildsBuildIdGetAsyncWithHttpInfo($build_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBuildV1BuildsBuildIdGetAsyncWithHttpInfo
     *
     * Get Build
     *
     * @param  int $build_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildV1BuildsBuildIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBuildV1BuildsBuildIdGetAsyncWithHttpInfo($build_id, string $contentType = self::contentTypes['getBuildV1BuildsBuildIdGet'][0])
    {
        $returnType = '\DeadlockApi\Model\Build';
        $request = $this->getBuildV1BuildsBuildIdGetRequest($build_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBuildV1BuildsBuildIdGet'
     *
     * @param  int $build_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildV1BuildsBuildIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getBuildV1BuildsBuildIdGetRequest($build_id, string $contentType = self::contentTypes['getBuildV1BuildsBuildIdGet'][0])
    {

        // verify the required parameter 'build_id' is set
        if ($build_id === null || (is_array($build_id) && count($build_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $build_id when calling getBuildV1BuildsBuildIdGet'
            );
        }


        $resourcePath = '/v1/builds/{build_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($build_id !== null) {
            $resourcePath = str_replace(
                '{' . 'build_id' . '}',
                ObjectSerializer::toPathValue($build_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getBuildsByHeroIdV1BuildsByHeroIdHeroIdGet
     *
     * Get Builds By Hero Id
     *
     * @param  int $hero_id hero_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildsByHeroIdV1BuildsByHeroIdHeroIdGet'] to see the possible values for this operation
     *
     * @throws \DeadlockApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \DeadlockApi\Model\Build[]|\DeadlockApi\Model\HTTPValidationError
     */
    public function getBuildsByHeroIdV1BuildsByHeroIdHeroIdGet($hero_id, string $contentType = self::contentTypes['getBuildsByHeroIdV1BuildsByHeroIdHeroIdGet'][0])
    {
        list($response) = $this->getBuildsByHeroIdV1BuildsByHeroIdHeroIdGetWithHttpInfo($hero_id, $contentType);
        return $response;
    }

    /**
     * Operation getBuildsByHeroIdV1BuildsByHeroIdHeroIdGetWithHttpInfo
     *
     * Get Builds By Hero Id
     *
     * @param  int $hero_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildsByHeroIdV1BuildsByHeroIdHeroIdGet'] to see the possible values for this operation
     *
     * @throws \DeadlockApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \DeadlockApi\Model\Build[]|\DeadlockApi\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBuildsByHeroIdV1BuildsByHeroIdHeroIdGetWithHttpInfo($hero_id, string $contentType = self::contentTypes['getBuildsByHeroIdV1BuildsByHeroIdHeroIdGet'][0])
    {
        $request = $this->getBuildsByHeroIdV1BuildsByHeroIdHeroIdGetRequest($hero_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\DeadlockApi\Model\Build[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\DeadlockApi\Model\Build[]' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\DeadlockApi\Model\Build[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\DeadlockApi\Model\HTTPValidationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\DeadlockApi\Model\HTTPValidationError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\DeadlockApi\Model\HTTPValidationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\DeadlockApi\Model\Build[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DeadlockApi\Model\Build[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DeadlockApi\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getBuildsByHeroIdV1BuildsByHeroIdHeroIdGetAsync
     *
     * Get Builds By Hero Id
     *
     * @param  int $hero_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildsByHeroIdV1BuildsByHeroIdHeroIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBuildsByHeroIdV1BuildsByHeroIdHeroIdGetAsync($hero_id, string $contentType = self::contentTypes['getBuildsByHeroIdV1BuildsByHeroIdHeroIdGet'][0])
    {
        return $this->getBuildsByHeroIdV1BuildsByHeroIdHeroIdGetAsyncWithHttpInfo($hero_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBuildsByHeroIdV1BuildsByHeroIdHeroIdGetAsyncWithHttpInfo
     *
     * Get Builds By Hero Id
     *
     * @param  int $hero_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildsByHeroIdV1BuildsByHeroIdHeroIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBuildsByHeroIdV1BuildsByHeroIdHeroIdGetAsyncWithHttpInfo($hero_id, string $contentType = self::contentTypes['getBuildsByHeroIdV1BuildsByHeroIdHeroIdGet'][0])
    {
        $returnType = '\DeadlockApi\Model\Build[]';
        $request = $this->getBuildsByHeroIdV1BuildsByHeroIdHeroIdGetRequest($hero_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBuildsByHeroIdV1BuildsByHeroIdHeroIdGet'
     *
     * @param  int $hero_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildsByHeroIdV1BuildsByHeroIdHeroIdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getBuildsByHeroIdV1BuildsByHeroIdHeroIdGetRequest($hero_id, string $contentType = self::contentTypes['getBuildsByHeroIdV1BuildsByHeroIdHeroIdGet'][0])
    {

        // verify the required parameter 'hero_id' is set
        if ($hero_id === null || (is_array($hero_id) && count($hero_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $hero_id when calling getBuildsByHeroIdV1BuildsByHeroIdHeroIdGet'
            );
        }


        $resourcePath = '/v1/builds/by-hero-id/{hero_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($hero_id !== null) {
            $resourcePath = str_replace(
                '{' . 'hero_id' . '}',
                ObjectSerializer::toPathValue($hero_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getBuildsByHeroNameV1BuildsByHeroNameHeroNameGet
     *
     * Get Builds By Hero Name
     *
     * @param  string $hero_name hero_name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildsByHeroNameV1BuildsByHeroNameHeroNameGet'] to see the possible values for this operation
     *
     * @throws \DeadlockApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \DeadlockApi\Model\Build[]|\DeadlockApi\Model\HTTPValidationError
     */
    public function getBuildsByHeroNameV1BuildsByHeroNameHeroNameGet($hero_name, string $contentType = self::contentTypes['getBuildsByHeroNameV1BuildsByHeroNameHeroNameGet'][0])
    {
        list($response) = $this->getBuildsByHeroNameV1BuildsByHeroNameHeroNameGetWithHttpInfo($hero_name, $contentType);
        return $response;
    }

    /**
     * Operation getBuildsByHeroNameV1BuildsByHeroNameHeroNameGetWithHttpInfo
     *
     * Get Builds By Hero Name
     *
     * @param  string $hero_name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildsByHeroNameV1BuildsByHeroNameHeroNameGet'] to see the possible values for this operation
     *
     * @throws \DeadlockApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \DeadlockApi\Model\Build[]|\DeadlockApi\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBuildsByHeroNameV1BuildsByHeroNameHeroNameGetWithHttpInfo($hero_name, string $contentType = self::contentTypes['getBuildsByHeroNameV1BuildsByHeroNameHeroNameGet'][0])
    {
        $request = $this->getBuildsByHeroNameV1BuildsByHeroNameHeroNameGetRequest($hero_name, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\DeadlockApi\Model\Build[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\DeadlockApi\Model\Build[]' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\DeadlockApi\Model\Build[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\DeadlockApi\Model\HTTPValidationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\DeadlockApi\Model\HTTPValidationError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\DeadlockApi\Model\HTTPValidationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\DeadlockApi\Model\Build[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DeadlockApi\Model\Build[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\DeadlockApi\Model\HTTPValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getBuildsByHeroNameV1BuildsByHeroNameHeroNameGetAsync
     *
     * Get Builds By Hero Name
     *
     * @param  string $hero_name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildsByHeroNameV1BuildsByHeroNameHeroNameGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBuildsByHeroNameV1BuildsByHeroNameHeroNameGetAsync($hero_name, string $contentType = self::contentTypes['getBuildsByHeroNameV1BuildsByHeroNameHeroNameGet'][0])
    {
        return $this->getBuildsByHeroNameV1BuildsByHeroNameHeroNameGetAsyncWithHttpInfo($hero_name, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBuildsByHeroNameV1BuildsByHeroNameHeroNameGetAsyncWithHttpInfo
     *
     * Get Builds By Hero Name
     *
     * @param  string $hero_name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildsByHeroNameV1BuildsByHeroNameHeroNameGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBuildsByHeroNameV1BuildsByHeroNameHeroNameGetAsyncWithHttpInfo($hero_name, string $contentType = self::contentTypes['getBuildsByHeroNameV1BuildsByHeroNameHeroNameGet'][0])
    {
        $returnType = '\DeadlockApi\Model\Build[]';
        $request = $this->getBuildsByHeroNameV1BuildsByHeroNameHeroNameGetRequest($hero_name, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBuildsByHeroNameV1BuildsByHeroNameHeroNameGet'
     *
     * @param  string $hero_name (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildsByHeroNameV1BuildsByHeroNameHeroNameGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getBuildsByHeroNameV1BuildsByHeroNameHeroNameGetRequest($hero_name, string $contentType = self::contentTypes['getBuildsByHeroNameV1BuildsByHeroNameHeroNameGet'][0])
    {

        // verify the required parameter 'hero_name' is set
        if ($hero_name === null || (is_array($hero_name) && count($hero_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $hero_name when calling getBuildsByHeroNameV1BuildsByHeroNameHeroNameGet'
            );
        }


        $resourcePath = '/v1/builds/by-hero-name/{hero_name}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($hero_name !== null) {
            $resourcePath = str_replace(
                '{' . 'hero_name' . '}',
                ObjectSerializer::toPathValue($hero_name),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getBuildsV1BuildsGet
     *
     * Get Builds
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildsV1BuildsGet'] to see the possible values for this operation
     *
     * @throws \DeadlockApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array<string,\DeadlockApi\Model\Build[]>
     */
    public function getBuildsV1BuildsGet(string $contentType = self::contentTypes['getBuildsV1BuildsGet'][0])
    {
        list($response) = $this->getBuildsV1BuildsGetWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation getBuildsV1BuildsGetWithHttpInfo
     *
     * Get Builds
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildsV1BuildsGet'] to see the possible values for this operation
     *
     * @throws \DeadlockApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of array<string,\DeadlockApi\Model\Build[]>, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBuildsV1BuildsGetWithHttpInfo(string $contentType = self::contentTypes['getBuildsV1BuildsGet'][0])
    {
        $request = $this->getBuildsV1BuildsGetRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('array<string,\DeadlockApi\Model\Build[]>' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('array<string,\DeadlockApi\Model\Build[]>' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'array<string,\DeadlockApi\Model\Build[]>', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'array<string,\DeadlockApi\Model\Build[]>';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'array<string,\DeadlockApi\Model\Build[]>',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getBuildsV1BuildsGetAsync
     *
     * Get Builds
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildsV1BuildsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBuildsV1BuildsGetAsync(string $contentType = self::contentTypes['getBuildsV1BuildsGet'][0])
    {
        return $this->getBuildsV1BuildsGetAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBuildsV1BuildsGetAsyncWithHttpInfo
     *
     * Get Builds
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildsV1BuildsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBuildsV1BuildsGetAsyncWithHttpInfo(string $contentType = self::contentTypes['getBuildsV1BuildsGet'][0])
    {
        $returnType = 'array<string,\DeadlockApi\Model\Build[]>';
        $request = $this->getBuildsV1BuildsGetRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBuildsV1BuildsGet'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBuildsV1BuildsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getBuildsV1BuildsGetRequest(string $contentType = self::contentTypes['getBuildsV1BuildsGet'][0])
    {


        $resourcePath = '/v1/builds';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
