<?php
/**
 * DefaultApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deadlock Data API
 *
 * API for Deadlock game data, containing builds and active matches
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getActiveMatchesV1ActiveMatchesGet
     *
     * Get Active Matches.
     *
     */
    public function testGetActiveMatchesV1ActiveMatchesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBuildV1BuildsBuildIdGet
     *
     * Get Build.
     *
     */
    public function testGetBuildV1BuildsBuildIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBuildsByHeroIdV1BuildsByHeroIdHeroIdGet
     *
     * Get Builds By Hero Id.
     *
     */
    public function testGetBuildsByHeroIdV1BuildsByHeroIdHeroIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBuildsByHeroNameV1BuildsByHeroNameHeroNameGet
     *
     * Get Builds By Hero Name.
     *
     */
    public function testGetBuildsByHeroNameV1BuildsByHeroNameHeroNameGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBuildsV1BuildsGet
     *
     * Get Builds.
     *
     */
    public function testGetBuildsV1BuildsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
